spring:
  profiles: dev
  data:
    mongodb:
      database: policymaintenance-db
#      uri: ${depktcosmosdb}
      # To be retrieved from the running environment, injected by
      #azure sdk as specified below.
      uri: mongodb://depktcosmosdev:FP8gFIN3eqw2fJV4BjAgCHYSQnM7oOEjHwbU2HERN3xdLYJce7r6spleStc1dES8E1yJOJ7J1KzZhvSFRwBesw==@depktcosmosdev.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@depktcosmosdev@

Azure:
  keyvault:
    client-id: 8ade2034-cba8-44c5-8cb6-515cb83a239d #app id
    uri: https://depkt-db-dev.vault.azure.net/
    tenant-id: adb53b4f-b05f-4dcb-a2e1-9111380568c3
    enabled: true
    client-key: FOr7Q~yXCsRPLcxCwhz13eIqIUjpFIZrBYA.E # cert key value

server:
  ports: 8080